# Generated by Django 4.0.3 on 2023-03-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('username', models.CharField(max_length=60)),
                ('ign', models.CharField(max_length=60)),
                ('lol_id', models.CharField(max_length=60)),
                ('discord_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
