# Generated by Django 4.1.7 on 2023-03-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_client_api', '0003_player_mmr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='lol',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='lol_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='mmr',
            field=models.IntegerField(default=0),
        ),
    ]
