# Generated by Django 4.1.7 on 2023-03-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_client_api', '0004_alter_player_lol_alter_player_lol_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mmr',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
